### PR TITLE
Improve svg and prepare print.

### PR DESCRIPTION
**Pull request by s31db**

### CODE REVIEW

**Comment by vpapadopou** [comment]
Hi! Thanks for your contribution! I was away on a trip so I just got to see your PR. Still interested in merging and creating a French version? I already took a look on your repository and would be happy to have the cards in multi-lingual format

**Comment by vpapadopou** [comment]
Reopening to discuss

**Comment by s31db** [comment]
Hi, thanks a lot! I've modified the layout of the printable pages to make the recto verso with folding. I added the String With logo. Would you like to keep the same modifications on the English version?
My idea is to have the English version serve as a base for the other languages, then let each one adapt its layout.

**Comment by vpapadopou** [comment]
I'm open to the idea, let me have a look of the next days and will get back to you :)

**Comment by s31db** [comment]
Ok, I've push new commits to adapt svg and prepare spanish version branche.

**Pull request closed without merging**
